services:
  _defaults:
    autowire: true

  App\Tests\Resource\Fixture\:
    resource: '%kernel.project_dir%/tests/Resource/Fixture/*'
    tags:
      - { "name": "doctrine.fixture.orm" }

  App\Shared\Infrastructure\Bus\CommandBus:
    public: true

  App\Shared\Infrastructure\Bus\QueryBus:
    public: true

  App\Currencies\Infrastructure\Service\CurrencyService:
    public: true
    arguments:
      $cachePool: '@app.cache.currencies'